/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcg_osom;

/**
 *
 * @author Andiargetlam
 */
public class Archieve extends javax.swing.JFrame {

    /**
     * Creates new form Archieve
     */
    public Archieve() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton4 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(null);

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(1024, 768));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1024, 768));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT025.png"))); // NOI18N
        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton4);
        jButton4.setBounds(80, 640, 100, 80);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT027.png"))); // NOI18N
        jButton12.setText("jButton1");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton12);
        jButton12.setBounds(280, 640, 90, 80);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT005.png"))); // NOI18N
        jButton20.setText("jButton1");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton20);
        jButton20.setBounds(470, 410, 100, 80);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT011.png"))); // NOI18N
        jButton21.setText("jButton1");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton21);
        jButton21.setBounds(470, 490, 100, 80);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT020.png"))); // NOI18N
        jButton22.setText("jButton1");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton22);
        jButton22.setBounds(470, 570, 100, 80);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT029.png"))); // NOI18N
        jButton23.setText("jButton1");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton23);
        jButton23.setBounds(470, 640, 100, 80);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT004.png"))); // NOI18N
        jButton15.setText("jButton1");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton15);
        jButton15.setBounds(370, 410, 100, 80);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT010.png"))); // NOI18N
        jButton17.setText("jButton1");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton17);
        jButton17.setBounds(370, 490, 100, 80);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT019.png"))); // NOI18N
        jButton18.setText("jButton1");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton18);
        jButton18.setBounds(370, 570, 100, 80);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT028.png"))); // NOI18N
        jButton19.setText("jButton1");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton19);
        jButton19.setBounds(370, 640, 100, 80);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT018.png"))); // NOI18N
        jButton13.setText("jButton1");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton13);
        jButton13.setBounds(280, 570, 90, 80);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT003.png"))); // NOI18N
        jButton14.setText("jButton1");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton14);
        jButton14.setBounds(280, 410, 90, 80);

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT006.png"))); // NOI18N
        jButton24.setText("jButton1");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton24);
        jButton24.setBounds(570, 410, 90, 80);

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT012.png"))); // NOI18N
        jButton25.setText("jButton1");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton25);
        jButton25.setBounds(570, 490, 90, 80);

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT021.png"))); // NOI18N
        jButton26.setText("jButton1");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton26);
        jButton26.setBounds(570, 570, 90, 80);

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT030.png"))); // NOI18N
        jButton27.setText("jButton1");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton27);
        jButton27.setBounds(570, 640, 90, 80);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT009.png"))); // NOI18N
        jButton16.setText("jButton1");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton16);
        jButton16.setBounds(280, 490, 90, 80);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT026.png"))); // NOI18N
        jButton7.setText("jButton1");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton7);
        jButton7.setBounds(180, 640, 100, 80);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT017.png"))); // NOI18N
        jButton8.setText("jButton1");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton8);
        jButton8.setBounds(180, 570, 100, 80);

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT013.png"))); // NOI18N
        jButton28.setText("jButton1");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton28);
        jButton28.setBounds(660, 490, 100, 80);

        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT015.png"))); // NOI18N
        jButton34.setText("jButton1");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton34);
        jButton34.setBounds(850, 490, 100, 80);

        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT024.png"))); // NOI18N
        jButton35.setText("jButton1");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton35);
        jButton35.setBounds(850, 570, 100, 80);

        jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT033.png"))); // NOI18N
        jButton36.setText("jButton1");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton36);
        jButton36.setBounds(850, 640, 100, 80);

        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT014.png"))); // NOI18N
        jButton31.setText("jButton1");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton31);
        jButton31.setBounds(760, 490, 90, 80);

        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT023.png"))); // NOI18N
        jButton32.setText("jButton1");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton32);
        jButton32.setBounds(760, 570, 90, 80);

        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT032.png"))); // NOI18N
        jButton33.setText("jButton1");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton33);
        jButton33.setBounds(760, 640, 90, 80);

        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT022.png"))); // NOI18N
        jButton29.setText("jButton1");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton29);
        jButton29.setBounds(660, 570, 100, 80);

        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT031.png"))); // NOI18N
        jButton30.setText("jButton1");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton30);
        jButton30.setBounds(660, 640, 100, 80);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT002.png"))); // NOI18N
        jButton9.setText("jButton1");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton9);
        jButton9.setBounds(180, 410, 100, 80);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT008.png"))); // NOI18N
        jButton11.setText("jButton1");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton11);
        jButton11.setBounds(180, 490, 100, 80);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT016.png"))); // NOI18N
        jButton6.setText("jButton1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton6);
        jButton6.setBounds(80, 570, 100, 80);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT001.png"))); // NOI18N
        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton3);
        jButton3.setBounds(80, 410, 100, 80);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT000.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton1);
        jButton1.setBounds(80, 330, 100, 80);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchieveThumbs/AT007.png"))); // NOI18N
        jButton5.setText("jButton1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton5);
        jButton5.setBounds(80, 490, 100, 80);

        jLabel10.setFont(new java.awt.Font("blzee", 0, 24)); // NOI18N
        jLabel10.setText(":");
        jLayeredPane1.add(jLabel10);
        jLabel10.setBounds(280, 240, 150, 50);

        jLabel9.setFont(new java.awt.Font("blzee", 0, 24)); // NOI18N
        jLabel9.setText(":");
        jLayeredPane1.add(jLabel9);
        jLabel9.setBounds(280, 190, 150, 50);

        jLabel8.setFont(new java.awt.Font("blzee", 0, 24)); // NOI18N
        jLabel8.setText(":");
        jLayeredPane1.add(jLabel8);
        jLabel8.setBounds(280, 130, 150, 50);

        jLabel7.setFont(new java.awt.Font("blzee", 0, 24)); // NOI18N
        jLabel7.setText(":");
        jLayeredPane1.add(jLabel7);
        jLabel7.setBounds(280, 80, 150, 50);

        jLabel6.setFont(new java.awt.Font("blzee", 0, 24)); // NOI18N
        jLabel6.setText("ATK / DEF ");
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(120, 240, 190, 50);

        jLabel5.setFont(new java.awt.Font("blzee", 0, 24)); // NOI18N
        jLabel5.setText("Type ");
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(120, 190, 190, 50);

        jLabel4.setFont(new java.awt.Font("blzee", 0, 24)); // NOI18N
        jLabel4.setText("Rarity");
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(120, 130, 160, 50);

        jLabel3.setFont(new java.awt.Font("blzee", 0, 24)); // NOI18N
        jLabel3.setText("ID / Name ");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(120, 80, 150, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArchievePotrait/AP001.png"))); // NOI18N
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(630, 70, 300, 250);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/archieve.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1024, 768));
        jLabel1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jLabel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 768);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID000 / Rick Astley 'Rick Roll'");
        jLabel8.setText("SSS Rank");
        jLabel9.setText("Gun");
        jLabel10.setText("6000 / 0");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP000.png")));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID001 / Epic Sax Guy");
        jLabel8.setText("S Rank");
        jLabel9.setText("Rock");
        jLabel10.setText("3000 / 1200");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP001.png")));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID002 / Troll Face");
        jLabel8.setText("S Rank");
        jLabel9.setText("Scissor");
        jLabel10.setText("3300 / 800");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP002.png")));
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID003 / But that was me DIO!");
        jLabel8.setText("S Rank");
        jLabel9.setText("Paper");
        jLabel10.setText("3000 / 1200");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP003.png")));
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID004 / Spanish Inquisition");
        jLabel8.setText("S Rank");
        jLabel9.setText("Rock");
        jLabel10.setText("2800 / 1600");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP004.png")));
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID005 / El Risitas");
        jLabel8.setText("S Rank");
        jLabel9.setText("Scissor");
        jLabel10.setText("2600 / 1800");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP005.png")));
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID006 / Buff Doge");
        jLabel8.setText("S Rank");
        jLabel9.setText("Paper");
        jLabel10.setText("3500 / 600");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP006.png")));
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID007 / Dorime");
        jLabel8.setText("A Rank");
        jLabel9.setText("Rock");
        jLabel10.setText("2300 / 1000");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP007.png")));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID008 / Cheems Doge");
        jLabel8.setText("A Rank");
        jLabel9.setText("Scissor");
        jLabel10.setText("2400 / 900");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP008.png")));
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID009 / Yao Ming");
        jLabel8.setText("A Rank");
        jLabel9.setText("Paper");
        jLabel10.setText("2200 / 1100");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP009.png")));
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID010 / Derp");
        jLabel8.setText("A Rank");
        jLabel9.setText("Rock");
        jLabel10.setText("2000 / 1500");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP010.png")));
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID011 / SpoNGeboB");
        jLabel8.setText("A Rank");
        jLabel9.setText("Scissor");
        jLabel10.setText("2100 / 1400");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP011.png")));
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID012 / Za Warudo");
        jLabel8.setText("A Rank");
        jLabel9.setText("Paper");
        jLabel10.setText("2600 / 800");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP012.png")));
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID013 / Woman Yelling to Cat");
        jLabel8.setText("A Rank");
        jLabel9.setText("Scissor");
        jLabel10.setText("2400 / 1100");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP013.png")));
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID014 / Cat getting Yelled");
        jLabel8.setText("A Rank");
        jLabel9.setText("Rock");
        jLabel10.setText("2400 / 1100");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP014.png")));
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID015 / Diccbudd");
        jLabel8.setText("A Rank");
        jLabel9.setText("Paper");
        jLabel10.setText("2100 / 1400");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP011.png")));
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID016 / Think Mark, Think!");
        jLabel8.setText("B Rank");
        jLabel9.setText("Rock");
        jLabel10.setText("1500 / 900");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP016.png")));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID017 / Mark, who can't think");
        jLabel8.setText("B Rank");
        jLabel9.setText("Scissor");
        jLabel10.setText("1500 / 900");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP017.png")));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID018 / The Blurred Girl");
        jLabel8.setText("B Rank");
        jLabel9.setText("Paper");
        jLabel10.setText("1000 / 1400");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP018.png")));
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID019 / The Distracted Guy");
        jLabel8.setText("B Rank");
        jLabel9.setText("Rock");
        jLabel10.setText("1100 / 1300");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP019.png")));
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID020 / Angry GF");
        jLabel8.setText("B Rank");
        jLabel9.setText("Scissor");
        jLabel10.setText("1200 / 1200");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP020.png")));
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID021 / Lol is u ded?");
        jLabel8.setText("B Rank");
        jLabel9.setText("Paper");
        jLabel10.setText("1200 / 1200");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP021.png")));
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID022 / Ded guy");
        jLabel8.setText("B Rank");
        jLabel9.setText("Rock");
        jLabel10.setText("1000 / 1500");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP022.png")));
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID023 / U see that guy?");
        jLabel8.setText("B Rank");
        jLabel9.setText("Scissor");
        jLabel10.setText("1500 / 700");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP023.png")));
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID024 / That guy");
        jLabel8.setText("B Rank");
        jLabel9.setText("Paper");
        jLabel10.setText("1400 / 900");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP024.png")));
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID025 / Now angry guy");
        jLabel8.setText("B Rank");
        jLabel9.setText("Rock");
        jLabel10.setText("1600 / 500");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP025.png")));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID026 / No U");
        jLabel8.setText("B Rank");
        jLabel9.setText("Scissor");
        jLabel10.setText("0 / 3000");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP026.png")));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID027 / Meme Man");
        jLabel8.setText("B Rank");
        jLabel9.setText("Paper");
        jLabel10.setText("1000 / 1000");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP027.png")));
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID028 / Orang Man");
        jLabel8.setText("B Rank");
        jLabel9.setText("Rock");
        jLabel10.setText("1000 / 1000");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP028.png")));
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID029 / Ara ara nee-san");
        jLabel8.setText("B Rank");
        jLabel9.setText("Scissor");
        jLabel10.setText("1500 / 600");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP029.png")));
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID030 / Shota-kun");
        jLabel8.setText("B Rank");
        jLabel9.setText("Paper");
        jLabel10.setText("1000 / 1200");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP030.png")));
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID031 / Lord Elon laughing");
        jLabel8.setText("B Rank");
        jLabel9.setText("Rock");
        jLabel10.setText("1300 / 900");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP031.png")));
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID032 / Elon's Dolphin.exe");
        jLabel8.setText("B Rank");
        jLabel9.setText("Scissor");
        jLabel10.setText("900 / 1300");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP032.png")));
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
        jLabel7.setText(": ID033 / Lord Zucc");
        jLabel8.setText("B Rank");
        jLabel9.setText("Paper");
        jLabel10.setText("2700 / 0");
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source Packages/ArchievePotrait/AP033.png")));
    }//GEN-LAST:event_jButton36ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Archieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Archieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Archieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Archieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Archieve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
