/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcg_osom;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author KuroNeko
 */
public class Deck_card extends javax.swing.JFrame {
Account acc = new Account();
    CrudImplement cli = new CrudImplement();
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    String account_id;
private card[] deck = new card[21];
private card inven_card;
private card[] inventory = new Card[100];
    /**
     * Creates new form Deck_card
     */
    public Deck_card() {
        initComponents();
        account_id = tcg_osom.Database.getUserId();
        getInventory();
        
        System.out.println(inventory);
    }

    private void getInventory(){
        conn = Database.config();
        String query = "select * from card where account_id = ?";
        try {
            pst = conn.prepareStatement(query);
            pst.setString(1,account_id);
            rs = pst.executeQuery();
            int i = 0;
            while(rs.next()){
                inven_card = new card(rs.getString("img"), rs.getString("highlight"), rs.getString("card_name"),rs.getString("type"), rs.getInt("att_power"), rs.getInt("def_power"), rs.getInt("id_card"), rs.getString("rarity"), rs.getString("selectImg"));
                inventory[i]=inven_card;
                i++;
            }
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void showInventory(){
        inventDeck1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/DeckThums/inventory[0].getImage")));
        inventDeck2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/DeckThums/inventory[1].getImage")));
        inventDeck3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/DeckThums/inventory[2].getImage")));
        inventDeck4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/DeckThums/inventory[3].getImage")));
        inventDeck5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/DeckThums/inventory[4].getImage")));
        inventDeck6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/DeckThums/inventory[5].getImage")));
        inventDeck7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/DeckThums/inventory[6].getImage")));
        inventDeck8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/DeckThums/inventory[7].getImage")));
        inventDeck9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/DeckThums/inventory[8].getImage")));
        inventDeck10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/DeckThums/inventory[9].getImage")));
        inventDeck11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/DeckThums/inventory[10].getImage")));
        inventDeck12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/DeckThums/inventory[11].getImage")));
        inventDeck13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/DeckThums/inventory[12].getImage")));
        inventDeck14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/DeckThums/inventory[13].getImage")));
        inventDeck15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/DeckThums/inventory[14].getImage")));
        inventDeck16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/DeckThums/inventory[0].getImage")));
        inventDeck17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/DeckThums/inventory[0].getImage")));
       
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        deckCard11 = new javax.swing.JButton();
        deckCard12 = new javax.swing.JButton();
        deckCard13 = new javax.swing.JButton();
        deckCard14 = new javax.swing.JButton();
        deckCard15 = new javax.swing.JButton();
        deckCard16 = new javax.swing.JButton();
        deckCard17 = new javax.swing.JButton();
        deckCard18 = new javax.swing.JButton();
        deckCard19 = new javax.swing.JButton();
        deckCard20 = new javax.swing.JButton();
        deckCard1 = new javax.swing.JButton();
        deckCard2 = new javax.swing.JButton();
        deckCard3 = new javax.swing.JButton();
        deckCard4 = new javax.swing.JButton();
        deckCard5 = new javax.swing.JButton();
        deckCard6 = new javax.swing.JButton();
        deckCard7 = new javax.swing.JButton();
        deckCard8 = new javax.swing.JButton();
        deckCard9 = new javax.swing.JButton();
        deckCard10 = new javax.swing.JButton();
        inventDeck1 = new javax.swing.JButton();
        inventDeck2 = new javax.swing.JButton();
        inventDeck3 = new javax.swing.JButton();
        inventDeck4 = new javax.swing.JButton();
        inventDeck5 = new javax.swing.JButton();
        inventDeck6 = new javax.swing.JButton();
        inventDeck7 = new javax.swing.JButton();
        inventDeck8 = new javax.swing.JButton();
        inventDeck9 = new javax.swing.JButton();
        inventDeck10 = new javax.swing.JButton();
        inventDeck11 = new javax.swing.JButton();
        inventDeck12 = new javax.swing.JButton();
        inventDeck13 = new javax.swing.JButton();
        inventDeck14 = new javax.swing.JButton();
        inventDeck15 = new javax.swing.JButton();
        inventDeck16 = new javax.swing.JButton();
        inventDeck17 = new javax.swing.JButton();
        inventDeck18 = new javax.swing.JButton();
        inventDeck19 = new javax.swing.JButton();
        inventDeck20 = new javax.swing.JButton();
        inventDeck21 = new javax.swing.JButton();
        inventDeck22 = new javax.swing.JButton();
        inventDeck23 = new javax.swing.JButton();
        inventDeck24 = new javax.swing.JButton();
        inventDeck25 = new javax.swing.JButton();
        inventDeck26 = new javax.swing.JButton();
        inventDeck27 = new javax.swing.JButton();
        inventDeck28 = new javax.swing.JButton();
        inventDeck29 = new javax.swing.JButton();
        inventDeck30 = new javax.swing.JButton();
        inventDeck31 = new javax.swing.JButton();
        inventDeck32 = new javax.swing.JButton();
        inventDeck33 = new javax.swing.JButton();
        inventDeck34 = new javax.swing.JButton();
        inventDeck35 = new javax.swing.JButton();
        inventDeck36 = new javax.swing.JButton();
        toogleCard = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 640));
        jPanel1.setLayout(null);

        deckCard11.setBorder(null);
        jPanel1.add(deckCard11);
        deckCard11.setBounds(56, 154, 75, 104);

        deckCard12.setBorder(null);
        jPanel1.add(deckCard12);
        deckCard12.setBounds(150, 154, 75, 104);

        deckCard13.setBorder(null);
        jPanel1.add(deckCard13);
        deckCard13.setBounds(246, 154, 75, 104);

        deckCard14.setBorder(null);
        jPanel1.add(deckCard14);
        deckCard14.setBounds(340, 154, 75, 104);

        deckCard15.setBorder(null);
        jPanel1.add(deckCard15);
        deckCard15.setBounds(435, 154, 75, 104);

        deckCard16.setBorder(null);
        jPanel1.add(deckCard16);
        deckCard16.setBounds(530, 154, 75, 104);

        deckCard17.setBorder(null);
        jPanel1.add(deckCard17);
        deckCard17.setBounds(625, 154, 75, 104);

        deckCard18.setBorder(null);
        jPanel1.add(deckCard18);
        deckCard18.setBounds(718, 154, 75, 104);

        deckCard19.setBorder(null);
        jPanel1.add(deckCard19);
        deckCard19.setBounds(810, 154, 75, 104);

        deckCard20.setBorder(null);
        jPanel1.add(deckCard20);
        deckCard20.setBounds(910, 154, 75, 104);

        deckCard1.setBorder(null);
        jPanel1.add(deckCard1);
        deckCard1.setBounds(55, 45, 75, 104);

        deckCard2.setBorder(null);
        jPanel1.add(deckCard2);
        deckCard2.setBounds(150, 45, 75, 104);

        deckCard3.setBorder(null);
        jPanel1.add(deckCard3);
        deckCard3.setBounds(245, 45, 75, 104);

        deckCard4.setBorder(null);
        jPanel1.add(deckCard4);
        deckCard4.setBounds(340, 45, 75, 104);

        deckCard5.setBorder(null);
        jPanel1.add(deckCard5);
        deckCard5.setBounds(435, 45, 75, 104);

        deckCard6.setBorder(null);
        jPanel1.add(deckCard6);
        deckCard6.setBounds(530, 45, 75, 104);

        deckCard7.setBorder(null);
        jPanel1.add(deckCard7);
        deckCard7.setBounds(625, 45, 75, 104);

        deckCard8.setBorder(null);
        jPanel1.add(deckCard8);
        deckCard8.setBounds(718, 45, 75, 104);

        deckCard9.setBorder(null);
        jPanel1.add(deckCard9);
        deckCard9.setBounds(813, 45, 75, 104);

        deckCard10.setBorder(null);
        jPanel1.add(deckCard10);
        deckCard10.setBounds(910, 45, 75, 104);

        inventDeck1.setBorder(null);
        inventDeck1.setContentAreaFilled(false);
        inventDeck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck1ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck1);
        inventDeck1.setBounds(41, 320, 50, 70);

        inventDeck2.setBorder(null);
        inventDeck2.setContentAreaFilled(false);
        inventDeck2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck2ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck2);
        inventDeck2.setBounds(93, 320, 50, 70);

        inventDeck3.setBorder(null);
        inventDeck3.setContentAreaFilled(false);
        inventDeck3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck3ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck3);
        inventDeck3.setBounds(144, 320, 50, 70);

        inventDeck4.setBorder(null);
        inventDeck4.setContentAreaFilled(false);
        inventDeck4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck4ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck4);
        inventDeck4.setBounds(196, 320, 50, 70);

        inventDeck5.setBorder(null);
        inventDeck5.setContentAreaFilled(false);
        inventDeck5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck5ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck5);
        inventDeck5.setBounds(245, 320, 50, 70);

        inventDeck6.setBorder(null);
        inventDeck6.setContentAreaFilled(false);
        inventDeck6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck6ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck6);
        inventDeck6.setBounds(296, 320, 50, 70);

        inventDeck7.setBorder(null);
        inventDeck7.setContentAreaFilled(false);
        inventDeck7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck7ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck7);
        inventDeck7.setBounds(347, 320, 50, 70);

        inventDeck8.setBorder(null);
        inventDeck8.setContentAreaFilled(false);
        inventDeck8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck8ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck8);
        inventDeck8.setBounds(398, 320, 50, 70);

        inventDeck9.setBorder(null);
        inventDeck9.setContentAreaFilled(false);
        inventDeck9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck9ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck9);
        inventDeck9.setBounds(449, 320, 50, 70);

        inventDeck10.setBorder(null);
        inventDeck10.setContentAreaFilled(false);
        inventDeck10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck10ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck10);
        inventDeck10.setBounds(40, 393, 50, 70);

        inventDeck11.setBorder(null);
        inventDeck11.setContentAreaFilled(false);
        inventDeck11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck11ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck11);
        inventDeck11.setBounds(90, 393, 50, 70);

        inventDeck12.setBorder(null);
        inventDeck12.setContentAreaFilled(false);
        inventDeck12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck12ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck12);
        inventDeck12.setBounds(144, 393, 50, 70);

        inventDeck13.setBorder(null);
        inventDeck13.setContentAreaFilled(false);
        inventDeck13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck13ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck13);
        inventDeck13.setBounds(196, 393, 50, 70);

        inventDeck14.setBorder(null);
        inventDeck14.setContentAreaFilled(false);
        inventDeck14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck14ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck14);
        inventDeck14.setBounds(245, 393, 50, 70);

        inventDeck15.setBorder(null);
        inventDeck15.setContentAreaFilled(false);
        inventDeck15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck15ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck15);
        inventDeck15.setBounds(297, 393, 50, 70);

        inventDeck16.setBorder(null);
        inventDeck16.setContentAreaFilled(false);
        inventDeck16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck16ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck16);
        inventDeck16.setBounds(350, 393, 50, 70);

        inventDeck17.setBorder(null);
        inventDeck17.setContentAreaFilled(false);
        inventDeck17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck17ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck17);
        inventDeck17.setBounds(400, 393, 50, 70);

        inventDeck18.setBorder(null);
        inventDeck18.setContentAreaFilled(false);
        inventDeck18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck18ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck18);
        inventDeck18.setBounds(450, 393, 50, 70);

        inventDeck19.setBorder(null);
        inventDeck19.setContentAreaFilled(false);
        inventDeck19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck19ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck19);
        inventDeck19.setBounds(40, 470, 50, 70);

        inventDeck20.setBorder(null);
        inventDeck20.setContentAreaFilled(false);
        inventDeck20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck20ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck20);
        inventDeck20.setBounds(90, 470, 50, 70);

        inventDeck21.setBorder(null);
        inventDeck21.setContentAreaFilled(false);
        inventDeck21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck21ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck21);
        inventDeck21.setBounds(140, 470, 50, 70);

        inventDeck22.setBorder(null);
        inventDeck22.setContentAreaFilled(false);
        inventDeck22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck22ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck22);
        inventDeck22.setBounds(200, 470, 50, 70);

        inventDeck23.setBorder(null);
        inventDeck23.setContentAreaFilled(false);
        inventDeck23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck23ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck23);
        inventDeck23.setBounds(240, 470, 50, 70);

        inventDeck24.setBorder(null);
        inventDeck24.setContentAreaFilled(false);
        inventDeck24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck24ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck24);
        inventDeck24.setBounds(300, 470, 50, 70);

        inventDeck25.setBorder(null);
        inventDeck25.setContentAreaFilled(false);
        inventDeck25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck25ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck25);
        inventDeck25.setBounds(350, 470, 50, 70);

        inventDeck26.setBorder(null);
        inventDeck26.setContentAreaFilled(false);
        inventDeck26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck26ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck26);
        inventDeck26.setBounds(400, 470, 50, 70);

        inventDeck27.setBorder(null);
        inventDeck27.setContentAreaFilled(false);
        inventDeck27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck27ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck27);
        inventDeck27.setBounds(450, 470, 50, 70);

        inventDeck28.setBorder(null);
        inventDeck28.setContentAreaFilled(false);
        inventDeck28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck28ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck28);
        inventDeck28.setBounds(450, 540, 50, 70);

        inventDeck29.setBorder(null);
        inventDeck29.setContentAreaFilled(false);
        inventDeck29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck29ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck29);
        inventDeck29.setBounds(400, 540, 50, 70);

        inventDeck30.setBorder(null);
        inventDeck30.setContentAreaFilled(false);
        inventDeck30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck30ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck30);
        inventDeck30.setBounds(350, 540, 50, 70);

        inventDeck31.setBorder(null);
        inventDeck31.setContentAreaFilled(false);
        inventDeck31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck31ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck31);
        inventDeck31.setBounds(300, 540, 50, 70);

        inventDeck32.setBorder(null);
        inventDeck32.setContentAreaFilled(false);
        inventDeck32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck32ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck32);
        inventDeck32.setBounds(240, 540, 50, 70);

        inventDeck33.setBorder(null);
        inventDeck33.setContentAreaFilled(false);
        inventDeck33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck33ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck33);
        inventDeck33.setBounds(200, 540, 50, 70);

        inventDeck34.setBorder(null);
        inventDeck34.setContentAreaFilled(false);
        inventDeck34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck34ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck34);
        inventDeck34.setBounds(140, 540, 50, 70);

        inventDeck35.setBorder(null);
        inventDeck35.setContentAreaFilled(false);
        inventDeck35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck35ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck35);
        inventDeck35.setBounds(90, 540, 50, 70);

        inventDeck36.setBorder(null);
        inventDeck36.setContentAreaFilled(false);
        inventDeck36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventDeck36ActionPerformed(evt);
            }
        });
        jPanel1.add(inventDeck36);
        inventDeck36.setBounds(40, 540, 50, 70);
        jPanel1.add(toogleCard);
        toogleCard.setBounds(560, 330, 197, 272);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/inventory.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1024, 640));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inventDeck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck1ActionPerformed

    private void inventDeck2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck2ActionPerformed

    private void inventDeck3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck3ActionPerformed

    private void inventDeck4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck4ActionPerformed

    private void inventDeck5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck5ActionPerformed

    private void inventDeck6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck6ActionPerformed

    private void inventDeck7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck7ActionPerformed

    private void inventDeck8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck8ActionPerformed

    private void inventDeck9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck9ActionPerformed

    private void inventDeck10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck10ActionPerformed

    private void inventDeck11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck11ActionPerformed

    private void inventDeck12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck12ActionPerformed

    private void inventDeck13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck13ActionPerformed

    private void inventDeck14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck14ActionPerformed

    private void inventDeck15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck15ActionPerformed

    private void inventDeck16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck16ActionPerformed

    private void inventDeck17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck17ActionPerformed

    private void inventDeck18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck18ActionPerformed

    private void inventDeck19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck19ActionPerformed

    private void inventDeck20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck20ActionPerformed

    private void inventDeck21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck21ActionPerformed

    private void inventDeck22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck22ActionPerformed

    private void inventDeck23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck23ActionPerformed

    private void inventDeck24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck24ActionPerformed

    private void inventDeck25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck25ActionPerformed

    private void inventDeck26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck26ActionPerformed

    private void inventDeck27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck27ActionPerformed

    private void inventDeck28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck28ActionPerformed

    private void inventDeck29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck29ActionPerformed

    private void inventDeck30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck30ActionPerformed

    private void inventDeck31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck31ActionPerformed

    private void inventDeck32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck32ActionPerformed

    private void inventDeck33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck33ActionPerformed

    private void inventDeck34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck34ActionPerformed

    private void inventDeck35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck35ActionPerformed

    private void inventDeck36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventDeck36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventDeck36ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deck_card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deck_card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deck_card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deck_card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deck_card().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deckCard1;
    private javax.swing.JButton deckCard10;
    private javax.swing.JButton deckCard11;
    private javax.swing.JButton deckCard12;
    private javax.swing.JButton deckCard13;
    private javax.swing.JButton deckCard14;
    private javax.swing.JButton deckCard15;
    private javax.swing.JButton deckCard16;
    private javax.swing.JButton deckCard17;
    private javax.swing.JButton deckCard18;
    private javax.swing.JButton deckCard19;
    private javax.swing.JButton deckCard2;
    private javax.swing.JButton deckCard20;
    private javax.swing.JButton deckCard3;
    private javax.swing.JButton deckCard4;
    private javax.swing.JButton deckCard5;
    private javax.swing.JButton deckCard6;
    private javax.swing.JButton deckCard7;
    private javax.swing.JButton deckCard8;
    private javax.swing.JButton deckCard9;
    private javax.swing.JButton inventDeck1;
    private javax.swing.JButton inventDeck10;
    private javax.swing.JButton inventDeck11;
    private javax.swing.JButton inventDeck12;
    private javax.swing.JButton inventDeck13;
    private javax.swing.JButton inventDeck14;
    private javax.swing.JButton inventDeck15;
    private javax.swing.JButton inventDeck16;
    private javax.swing.JButton inventDeck17;
    private javax.swing.JButton inventDeck18;
    private javax.swing.JButton inventDeck19;
    private javax.swing.JButton inventDeck2;
    private javax.swing.JButton inventDeck20;
    private javax.swing.JButton inventDeck21;
    private javax.swing.JButton inventDeck22;
    private javax.swing.JButton inventDeck23;
    private javax.swing.JButton inventDeck24;
    private javax.swing.JButton inventDeck25;
    private javax.swing.JButton inventDeck26;
    private javax.swing.JButton inventDeck27;
    private javax.swing.JButton inventDeck28;
    private javax.swing.JButton inventDeck29;
    private javax.swing.JButton inventDeck3;
    private javax.swing.JButton inventDeck30;
    private javax.swing.JButton inventDeck31;
    private javax.swing.JButton inventDeck32;
    private javax.swing.JButton inventDeck33;
    private javax.swing.JButton inventDeck34;
    private javax.swing.JButton inventDeck35;
    private javax.swing.JButton inventDeck36;
    private javax.swing.JButton inventDeck4;
    private javax.swing.JButton inventDeck5;
    private javax.swing.JButton inventDeck6;
    private javax.swing.JButton inventDeck7;
    private javax.swing.JButton inventDeck8;
    private javax.swing.JButton inventDeck9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel toogleCard;
    // End of variables declaration//GEN-END:variables
}
