/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcg_osom;

/**
 *
 * @author Andiargetlam
 */
public class DeckCard extends javax.swing.JFrame {

    /**
     * Creates new form Collection
     */
    public DeckCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CardPreview = new javax.swing.JLabel();
        Grid7 = new javax.swing.JButton();
        Grid1 = new javax.swing.JButton();
        Grid2 = new javax.swing.JButton();
        Grid3 = new javax.swing.JButton();
        Grid4 = new javax.swing.JButton();
        Grid5 = new javax.swing.JButton();
        Grid6 = new javax.swing.JButton();
        Grid14 = new javax.swing.JButton();
        Grid13 = new javax.swing.JButton();
        Grid12 = new javax.swing.JButton();
        Grid11 = new javax.swing.JButton();
        Grid10 = new javax.swing.JButton();
        Grid9 = new javax.swing.JButton();
        Grid8 = new javax.swing.JButton();
        Grid21 = new javax.swing.JButton();
        Grid20 = new javax.swing.JButton();
        Grid19 = new javax.swing.JButton();
        Grid18 = new javax.swing.JButton();
        Grid17 = new javax.swing.JButton();
        Grid16 = new javax.swing.JButton();
        Grid15 = new javax.swing.JButton();
        description4 = new javax.swing.JLabel();
        description1 = new javax.swing.JLabel();
        description2 = new javax.swing.JLabel();
        description3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(CardPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 340, 490));

        Grid7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid7.png"))); // NOI18N
        Grid7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid7ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 70, 90, 130));

        Grid1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid1.png"))); // NOI18N
        Grid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid1ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 90, 130));

        Grid2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid2.png"))); // NOI18N
        Grid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid2ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 90, 130));

        Grid3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid3.png"))); // NOI18N
        Grid3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid3ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 90, 130));

        Grid4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid4.png"))); // NOI18N
        Grid4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid4ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 90, 130));

        Grid5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid5.png"))); // NOI18N
        Grid5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid5ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 90, 130));

        Grid6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid6.png"))); // NOI18N
        Grid6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid6ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, 90, 130));

        Grid14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid14.png"))); // NOI18N
        Grid14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid14ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid14, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 200, 90, 130));

        Grid13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid13.png"))); // NOI18N
        Grid13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid13ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid13, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, 90, 130));

        Grid12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid12.png"))); // NOI18N
        Grid12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid12ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 90, 130));

        Grid11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid11.png"))); // NOI18N
        Grid11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid11ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 90, 130));

        Grid10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid10.png"))); // NOI18N
        Grid10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid10ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 90, 130));

        Grid9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid9.png"))); // NOI18N
        Grid9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid9ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 90, 130));

        Grid8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid8.png"))); // NOI18N
        Grid8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid8ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 90, 130));

        Grid21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid21.png"))); // NOI18N
        Grid21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid21ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid21, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 330, 90, 130));

        Grid20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid20.png"))); // NOI18N
        Grid20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid20ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid20, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, 90, 130));

        Grid19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid19.png"))); // NOI18N
        Grid19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid19ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid19, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 90, 130));

        Grid18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid18.png"))); // NOI18N
        Grid18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid18ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid18, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 90, 130));

        Grid17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid17.png"))); // NOI18N
        Grid17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid17ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 90, 130));

        Grid16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid16.png"))); // NOI18N
        Grid16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid16ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 90, 130));

        Grid15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColGrid/Grid15.png"))); // NOI18N
        Grid15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid15ActionPerformed(evt);
            }
        });
        getContentPane().add(Grid15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 90, 130));

        description4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        description4.setText("Desc :");
        getContentPane().add(description4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 600, 560, 40));

        description1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        description1.setText("Name :");
        getContentPane().add(description1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 560, 40));

        description2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        description2.setText("Class : ");
        getContentPane().add(description2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 560, 40));

        description3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        description3.setText("Type :");
        getContentPane().add(description3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 570, 40));

        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnClose.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 50, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CardList.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Grid7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid7ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : Rage Derp");
        description2.setText("Class : A");
        description3.setText("Type : Scissor");
        description4.setText("Desc : AAAAAAAAAHHHH");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co7.png")));
    }//GEN-LAST:event_Grid7ActionPerformed

    private void Grid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid1ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : Buff Doge");
        description2.setText("Class : S");
        description3.setText("Type : Scissor");
        description4.setText("Desc : He's a Good Boi");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co1.png")));
    }//GEN-LAST:event_Grid1ActionPerformed

    private void Grid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid2ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : Rick'Roll");
        description2.setText("Class : S");
        description3.setText("Type : Paper");
        description4.setText("Desc : NEVER GONNA GIVE YOU UP");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co2.png")));
    }//GEN-LAST:event_Grid2ActionPerformed

    private void Grid3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid3ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : U Mad Bro?");
        description2.setText("Class : S");
        description3.setText("Type : Rock");
        description4.setText("Desc : TROLOLOLOLO");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co3.png")));
    }//GEN-LAST:event_Grid3ActionPerformed

    private void Grid4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid4ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : meme man");
        description2.setText("Class : A");
        description3.setText("Type : Scissor");
        description4.setText("Desc : cool and good");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co4.png")));
    }//GEN-LAST:event_Grid4ActionPerformed

    private void Grid5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid5ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : Pepe the Frog");
        description2.setText("Class : A");
        description3.setText("Type : Rock");
        description4.setText("Desc : feels good man");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co5.png")));
    }//GEN-LAST:event_Grid5ActionPerformed

    private void Grid6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid6ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : Doge");
        description2.setText("Class : A");
        description3.setText("Type : Paper");
        description4.setText("Desc : Such doge, much wow. Wow");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co6.png")));
    }//GEN-LAST:event_Grid6ActionPerformed

    private void Grid14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid14ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : Even Raged Guy");
        description2.setText("Class : B");
        description3.setText("Type : Rock");
        description4.setText("Desc : WRONG CARD NAME!!DELETE THE FAKE PNG!!");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co14.png")));
    }//GEN-LAST:event_Grid14ActionPerformed

    private void Grid13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid13ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : Also Rage Guy");
        description2.setText("Class : B");
        description3.setText("Type : Scissor");
        description4.setText("Desc : WHY IS THERE TWO OF ME");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co13.png")));
    }//GEN-LAST:event_Grid13ActionPerformed

    private void Grid12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid12ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : Yao Ming");
        description2.setText("Class : B");
        description3.setText("Type : Paper");
        description4.setText("Desc : B*tch Please");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co12.png")));
    }//GEN-LAST:event_Grid12ActionPerformed

    private void Grid11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid11ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : Cereal Guy");
        description2.setText("Class : B");
        description3.setText("Type : Rock");
        description4.setText("Desc : Oh F* i just ate a bowl of rock");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co11.png")));
    }//GEN-LAST:event_Grid11ActionPerformed

    private void Grid10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid10ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : Diccbudd");
        description2.setText("Class : B");
        description3.setText("Type : Scissor");
        description4.setText("Desc : Diccbudd");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co10.png")));
    }//GEN-LAST:event_Grid10ActionPerformed

    private void Grid9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid9ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : Disappointed Troll");
        description2.setText("Class : A");
        description3.setText("Type : Paper");
        description4.setText("Desc : Epstein didn't kill himself");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co9.png")));
    }//GEN-LAST:event_Grid9ActionPerformed

    private void Grid8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid8ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : Triggered Boi");
        description2.setText("Class : A");
        description3.setText("Type : Rock");
        description4.setText("Desc : Why is my type is a rock");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co8.png")));
    }//GEN-LAST:event_Grid8ActionPerformed

    private void Grid21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid21ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : Herp");
        description2.setText("Class : B");
        description3.setText("Type : Paper");
        description4.setText("Desc : Royal Flush! Skakmat!");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co21.png")));
    }//GEN-LAST:event_Grid21ActionPerformed

    private void Grid20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid20ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : Bonk Doge");
        description2.setText("Class : B");
        description3.setText("Type : Rock");
        description4.setText("Desc : BONK!");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co20.png")));
    }//GEN-LAST:event_Grid20ActionPerformed

    private void Grid19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid19ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : Derp");
        description2.setText("Class : B");
        description3.setText("Type : Scissor");
        description4.setText("Desc : Yep the name is Derp");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co19.png")));
    }//GEN-LAST:event_Grid19ActionPerformed

    private void Grid18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid18ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : LOLOL");
        description2.setText("Class : B");
        description3.setText("Type : Paper");
        description4.setText("Desc : LOLOLOL");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co18.png")));
    }//GEN-LAST:event_Grid18ActionPerformed

    private void Grid17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid17ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : Bully Maguire");
        description2.setText("Class : B");
        description3.setText("Type : Rock");
        description4.setText("Desc : I'm gonna put some dirt in your eye");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co17.png")));
    }//GEN-LAST:event_Grid17ActionPerformed

    private void Grid16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid16ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : Triggered Guy");
        description2.setText("Class : B");
        description3.setText("Type : Scissor");
        description4.setText("Desc : CLOSE UP FACE");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co16.png")));
    }//GEN-LAST:event_Grid16ActionPerformed

    private void Grid15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid15ActionPerformed
        // TODO add your handling code here:
        description1.setText("Name : Also Cereal Guy");
        description2.setText("Class : B");
        description3.setText("Type : Paper");
        description4.setText("Desc : i forgot to put milk on the cereal");
        CardPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ColHighlight/Co15.png")));
    }//GEN-LAST:event_Grid15ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnClose-Hover.png")));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnClose.png")));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeckCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeckCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeckCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeckCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeckCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CardPreview;
    private javax.swing.JButton Grid1;
    private javax.swing.JButton Grid10;
    private javax.swing.JButton Grid11;
    private javax.swing.JButton Grid12;
    private javax.swing.JButton Grid13;
    private javax.swing.JButton Grid14;
    private javax.swing.JButton Grid15;
    private javax.swing.JButton Grid16;
    private javax.swing.JButton Grid17;
    private javax.swing.JButton Grid18;
    private javax.swing.JButton Grid19;
    private javax.swing.JButton Grid2;
    private javax.swing.JButton Grid20;
    private javax.swing.JButton Grid21;
    private javax.swing.JButton Grid3;
    private javax.swing.JButton Grid4;
    private javax.swing.JButton Grid5;
    private javax.swing.JButton Grid6;
    private javax.swing.JButton Grid7;
    private javax.swing.JButton Grid8;
    private javax.swing.JButton Grid9;
    private javax.swing.JLabel background;
    private javax.swing.JLabel description1;
    private javax.swing.JLabel description2;
    private javax.swing.JLabel description3;
    private javax.swing.JLabel description4;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
