/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcg_osom;

import java.util.LinkedList;
import javax.swing.JLabel;

/**
 *
 * @author FX8800
 */
public class GachaWindow1 extends javax.swing.JFrame {

    /**
     * Creates new form GachaWindow1
     */
    public GachaWindow1() {
        initComponents();
        pict = new LinkedList<JLabel>();
        characters = new LinkedList<JLabel>();
        
        pict.add(img0);
        characters.add(character0);
         roll();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        character0 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        counterResult = new javax.swing.JLabel();
        img0 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtGold = new javax.swing.JLabel();
        txtGem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        statisticPanel = new javax.swing.JPanel();
        scrollArea = new javax.swing.JScrollPane();
        infoArea = new javax.swing.JTextArea();
        percentButton = new javax.swing.JButton();
        rarityButton = new javax.swing.JButton();
        quantityButton = new javax.swing.JButton();
        statTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        character0.setText("<html>[SSR]<br/>Rodriguezazora</html>");
        jLayeredPane1.add(character0);
        character0.setBounds(220, 430, 80, 40);

        jButton3.setText("PULL AGAIN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton3);
        jButton3.setBounds(20, 530, 120, 23);

        counterResult.setText("jLabel1");
        jLayeredPane1.add(counterResult);
        counterResult.setBounds(170, 530, 220, 14);
        jLayeredPane1.add(img0);
        img0.setBounds(170, 200, 168, 223);

        jButton4.setText("Market");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton4);
        jButton4.setBounds(430, 0, 80, 50);

        jButton5.setText("10 PULL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton5);
        jButton5.setBounds(390, 530, 120, 23);

        txtGold.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtGold.setForeground(new java.awt.Color(255, 255, 255));
        txtGold.setText("Gold");
        jLayeredPane1.add(txtGold);
        txtGold.setBounds(60, 10, 33, 19);

        txtGem.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtGem.setForeground(new java.awt.Color(255, 255, 255));
        txtGem.setText("Gems");
        jLayeredPane1.add(txtGem);
        txtGem.setBounds(270, 10, 40, 19);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/Gold.png"))); // NOI18N
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(0, 0, 206, 49);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/Gem.png"))); // NOI18N
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(210, 0, 206, 49);

        jTabbedPane1.addTab("Gacha", jLayeredPane1);

        statisticPanel.setPreferredSize(new java.awt.Dimension(640, 480));

        scrollArea.setHorizontalScrollBar(null);

        infoArea.setEditable(false);
        infoArea.setColumns(20);
        infoArea.setRows(5);
        scrollArea.setViewportView(infoArea);

        percentButton.setText("Percentage of rarity characters founded.");
        percentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentButtonActionPerformed(evt);
            }
        });

        rarityButton.setText("Quantity of characters by rarity.");
        rarityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rarityButtonActionPerformed(evt);
            }
        });

        quantityButton.setText("Quantity, Name and Rarity of all founded characters.");
        quantityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityButtonActionPerformed(evt);
            }
        });

        statTitle.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        statTitle.setText("Statistics");

        javax.swing.GroupLayout statisticPanelLayout = new javax.swing.GroupLayout(statisticPanel);
        statisticPanel.setLayout(statisticPanelLayout);
        statisticPanelLayout.setHorizontalGroup(
            statisticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statisticPanelLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(scrollArea, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statisticPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statisticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rarityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
            .addGroup(statisticPanelLayout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(statTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        statisticPanelLayout.setVerticalGroup(
            statisticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statTitle)
                .addGap(14, 14, 14)
                .addComponent(scrollArea, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(percentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rarityButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantityButton)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Statistics", statisticPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        roll();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Market market = new Market();
        market.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void percentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentButtonActionPerformed
        infoArea.setText("");
        PoolResult result = new PoolResult(Gacha.characters);
        infoArea.append(result.getResultInPercentage());
    }//GEN-LAST:event_percentButtonActionPerformed

    private void rarityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rarityButtonActionPerformed
        infoArea.setText("");
        PoolResult result = new PoolResult(Gacha.characters);
        infoArea.append(result.getResultInQuantity());
    }//GEN-LAST:event_rarityButtonActionPerformed

    private void quantityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityButtonActionPerformed
        infoArea.setText("");
        PoolResult result = new PoolResult(Gacha.characters);
        result.getResultListOfCharacters().forEach((n) ->
            infoArea.append(String.format("%s%n", n)));
    }//GEN-LAST:event_quantityButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GachaWindow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GachaWindow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GachaWindow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GachaWindow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GachaWindow1().setVisible(true);
            }
        });
        
    }
    private LinkedList<JLabel> pict;	
    private LinkedList<JLabel> characters;
    
    private void roll(){
    	int index = 0;
        for (PoolModel prize : Gacha.huntMenu1()) {
			characters.get(index).setText("<html>"+ prize.getParsedTier() + "<br/>"+ prize.getName() 
                                + "</html>" );
                        pict.get(index).setText("<html>" + prize.getPict());
			index++;
        }
        counterResult.setText(Gacha.counterResult());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel character0;
    private javax.swing.JLabel counterResult;
    private javax.swing.JLabel img0;
    private javax.swing.JTextArea infoArea;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton percentButton;
    private javax.swing.JButton quantityButton;
    private javax.swing.JButton rarityButton;
    private javax.swing.JScrollPane scrollArea;
    private javax.swing.JLabel statTitle;
    private javax.swing.JPanel statisticPanel;
    private javax.swing.JLabel txtGem;
    private javax.swing.JLabel txtGold;
    // End of variables declaration//GEN-END:variables
}
