/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcg_osom;

import java.util.LinkedList;
import javax.swing.JLabel;

/**
 *
 * @author FX8800
 */
public class GachaWindow2 extends javax.swing.JFrame {

    /**
     * Creates new form GachaWindow1
     */
    public GachaWindow2() {
        initComponents();
        imgs = new LinkedList<JLabel>();
        characters = new LinkedList<JLabel>();
        
        imgs.add(img0);
        characters.add(character0);
         roll();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton3 = new javax.swing.JButton();
        counterResult = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        img0 = new javax.swing.JLabel();
        character0 = new javax.swing.JLabel();
        character1 = new javax.swing.JLabel();
        character2 = new javax.swing.JLabel();
        character3 = new javax.swing.JLabel();
        character4 = new javax.swing.JLabel();
        character5 = new javax.swing.JLabel();
        character6 = new javax.swing.JLabel();
        character7 = new javax.swing.JLabel();
        character8 = new javax.swing.JLabel();
        character9 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img4 = new javax.swing.JLabel();
        img5 = new javax.swing.JLabel();
        img6 = new javax.swing.JLabel();
        img7 = new javax.swing.JLabel();
        img8 = new javax.swing.JLabel();
        img9 = new javax.swing.JLabel();
        txtGold = new javax.swing.JLabel();
        txtGem = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        statisticPanel = new javax.swing.JPanel();
        scrollArea = new javax.swing.JScrollPane();
        infoArea = new javax.swing.JTextArea();
        percentButton = new javax.swing.JButton();
        rarityButton = new javax.swing.JButton();
        quantityButton = new javax.swing.JButton();
        statTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("PULL AGAIN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton3);
        jButton3.setBounds(20, 530, 120, 23);

        counterResult.setText("Pull");
        jLayeredPane1.add(counterResult);
        counterResult.setBounds(250, 530, 220, 14);

        jButton4.setText("Market");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton4);
        jButton4.setBounds(600, 10, 120, 23);

        jButton5.setText("10 PULL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton5);
        jButton5.setBounds(600, 530, 120, 23);

        panel1.setLayout(null);
        panel1.add(img0);
        img0.setBounds(590, 180, 80, 70);

        character0.setText("<html>[SSR]<br/>Rodriguezazora</html>");
        panel1.add(character0);
        character0.setBounds(590, 250, 90, 40);

        character1.setText("<html>[SSR]<br/>Rodriguezazora</html>");
        panel1.add(character1);
        character1.setBounds(30, 130, 90, 40);

        character2.setText("<html>[SSR]<br/>Rodriguezazora</html>");
        panel1.add(character2);
        character2.setBounds(170, 130, 90, 40);

        character3.setText("<html>[SSR]<br/>Rodriguezazora</html>");
        panel1.add(character3);
        character3.setBounds(310, 130, 90, 40);

        character4.setText("<html>[SSR]<br/>Rodriguezazora</html>");
        panel1.add(character4);
        character4.setBounds(450, 130, 90, 40);

        character5.setText("<html>[SSR]<br/>Rodriguezazora</html>");
        panel1.add(character5);
        character5.setBounds(590, 130, 90, 40);

        character6.setText("<html>[SSR]<br/>Rodriguezazora</html>");
        panel1.add(character6);
        character6.setBounds(40, 250, 90, 40);

        character7.setText("<html>[SSR]<br/>Rodriguezazora</html>");
        panel1.add(character7);
        character7.setBounds(170, 250, 90, 40);

        character8.setText("<html>[SSR]<br/>Rodriguezazora</html>");
        panel1.add(character8);
        character8.setBounds(310, 250, 90, 40);

        character9.setText("<html>[SSR]<br/>Rodriguezazora</html>");
        panel1.add(character9);
        character9.setBounds(450, 250, 90, 40);
        panel1.add(img1);
        img1.setBounds(30, 60, 80, 70);
        panel1.add(img2);
        img2.setBounds(170, 60, 80, 70);
        panel1.add(img3);
        img3.setBounds(310, 60, 80, 70);
        panel1.add(img4);
        img4.setBounds(450, 60, 80, 70);
        panel1.add(img5);
        img5.setBounds(590, 60, 80, 70);
        panel1.add(img6);
        img6.setBounds(40, 180, 80, 70);
        panel1.add(img7);
        img7.setBounds(170, 180, 80, 70);
        panel1.add(img8);
        img8.setBounds(310, 180, 80, 70);
        panel1.add(img9);
        img9.setBounds(450, 180, 80, 70);

        jLayeredPane1.add(panel1);
        panel1.setBounds(10, 50, 710, 420);

        txtGold.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtGold.setForeground(new java.awt.Color(255, 255, 255));
        txtGold.setText("Gold");
        jLayeredPane1.add(txtGold);
        txtGold.setBounds(70, 10, 33, 19);

        txtGem.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtGem.setForeground(new java.awt.Color(255, 255, 255));
        txtGem.setText("Gems");
        jLayeredPane1.add(txtGem);
        txtGem.setBounds(280, 10, 40, 19);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/Gem.png"))); // NOI18N
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(220, 0, 206, 49);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/Gold.png"))); // NOI18N
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(10, 0, 206, 49);

        jTabbedPane1.addTab("Gacha", jLayeredPane1);

        statisticPanel.setPreferredSize(new java.awt.Dimension(640, 480));

        scrollArea.setHorizontalScrollBar(null);

        infoArea.setEditable(false);
        infoArea.setColumns(20);
        infoArea.setRows(5);
        scrollArea.setViewportView(infoArea);

        percentButton.setText("Percentage of rarity characters founded.");
        percentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentButtonActionPerformed(evt);
            }
        });

        rarityButton.setText("Quantity of characters by rarity.");
        rarityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rarityButtonActionPerformed(evt);
            }
        });

        quantityButton.setText("Quantity, Name and Rarity of all founded characters.");
        quantityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityButtonActionPerformed(evt);
            }
        });

        statTitle.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        statTitle.setText("Statistics");

        javax.swing.GroupLayout statisticPanelLayout = new javax.swing.GroupLayout(statisticPanel);
        statisticPanel.setLayout(statisticPanelLayout);
        statisticPanelLayout.setHorizontalGroup(
            statisticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statisticPanelLayout.createSequentialGroup()
                .addGap(0, 133, Short.MAX_VALUE)
                .addComponent(scrollArea, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(statisticPanelLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(statisticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rarityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statisticPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(statTitle)
                .addGap(331, 331, 331))
        );
        statisticPanelLayout.setVerticalGroup(
            statisticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(statTitle)
                .addGap(18, 18, 18)
                .addComponent(scrollArea, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(percentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rarityButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantityButton)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Statistics", statisticPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        roll();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Market market = new Market();
        market.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void percentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentButtonActionPerformed
        infoArea.setText("");
        PoolResult result = new PoolResult(Gacha.characters);
        infoArea.append(result.getResultInPercentage());
    }//GEN-LAST:event_percentButtonActionPerformed

    private void rarityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rarityButtonActionPerformed
        infoArea.setText("");
        PoolResult result = new PoolResult(Gacha.characters);
        infoArea.append(result.getResultInQuantity());
    }//GEN-LAST:event_rarityButtonActionPerformed

    private void quantityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityButtonActionPerformed
        infoArea.setText("");
        PoolResult result = new PoolResult(Gacha.characters);
        result.getResultListOfCharacters().forEach((n) ->
            infoArea.append(String.format("%s%n", n)));
    }//GEN-LAST:event_quantityButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GachaWindow2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GachaWindow2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GachaWindow2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GachaWindow2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GachaWindow2().setVisible(true);
            }
        });
        
    }
    private LinkedList<JLabel> imgs;	
    private LinkedList<JLabel> characters;
    
    private void roll(){
    	int index = 0;
        for (PoolModel prize : Gacha.huntMenu1()) {
			characters.get(index).setText("<html>"+ prize.getParsedTier() + "<br/>"+ prize.getName() + "</html>");
			index++;
        }
        counterResult.setText(Gacha.counterResult());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel character0;
    private javax.swing.JLabel character1;
    private javax.swing.JLabel character2;
    private javax.swing.JLabel character3;
    private javax.swing.JLabel character4;
    private javax.swing.JLabel character5;
    private javax.swing.JLabel character6;
    private javax.swing.JLabel character7;
    private javax.swing.JLabel character8;
    private javax.swing.JLabel character9;
    private javax.swing.JLabel counterResult;
    private javax.swing.JLabel img0;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JLabel img6;
    private javax.swing.JLabel img7;
    private javax.swing.JLabel img8;
    private javax.swing.JLabel img9;
    private javax.swing.JTextArea infoArea;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Panel panel1;
    private javax.swing.JButton percentButton;
    private javax.swing.JButton quantityButton;
    private javax.swing.JButton rarityButton;
    private javax.swing.JScrollPane scrollArea;
    private javax.swing.JLabel statTitle;
    private javax.swing.JPanel statisticPanel;
    private javax.swing.JLabel txtGem;
    private javax.swing.JLabel txtGold;
    // End of variables declaration//GEN-END:variables
}
