/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcg_osom;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author KuroNeko
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
//        this.setSize(layar.width,layar.height);       
        int kiri = (layar.width-this.getSize().width)/2;       
        int atas = (layar.height-this.getSize().height)/2;       
        setLocation(kiri,atas);       
//        Background.setBounds(0,0,layar.width,(int) Math.round(layar.height-(layar.height*0.1)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        btnPlay = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnShop = new javax.swing.JButton();
        btnCard = new javax.swing.JButton();
        btnGuide = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TCG Osom");
        setIconImage(getIconImage());
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPlay.setBackground(new java.awt.Color(255, 51, 51));
        btnPlay.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnPlay.setText("Play");
        btnPlay.setBorderPainted(false);
        getContentPane().add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 190, 90));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        btnShop.setBackground(new java.awt.Color(51, 51, 51));
        btnShop.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnShop.setForeground(new java.awt.Color(255, 255, 255));
        btnShop.setText("Shop");
        btnShop.setBorderPainted(false);
        btnShop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnShop.setIconTextGap(20);
        btnShop.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel2.add(btnShop);

        btnCard.setBackground(new java.awt.Color(51, 51, 51));
        btnCard.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCard.setForeground(new java.awt.Color(255, 255, 255));
        btnCard.setText("Card Collection");
        btnCard.setBorderPainted(false);
        btnCard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCard.setIconTextGap(20);
        btnCard.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel2.add(btnCard);

        btnGuide.setBackground(new java.awt.Color(51, 51, 51));
        btnGuide.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnGuide.setForeground(new java.awt.Color(255, 255, 255));
        btnGuide.setText("Guide");
        btnGuide.setBorderPainted(false);
        btnGuide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuide.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuide.setIconTextGap(20);
        btnGuide.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel2.add(btnGuide);

        btnAbout.setBackground(new java.awt.Color(51, 51, 51));
        btnAbout.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(255, 255, 255));
        btnAbout.setText("About");
        btnAbout.setBorderPainted(false);
        btnAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbout.setIconTextGap(20);
        btnAbout.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel2.add(btnAbout);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("jButton1");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(20);
        jButton1.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 1010, 100));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(100, 20, 110, 40);
        jPanel3.add(jLabel1);
        jLabel1.setBounds(30, 30, 50, 50);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
//       setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Menu menu = new Menu();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnCard;
    private javax.swing.JButton btnGuide;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnShop;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
