/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcg_osom;

import java.awt.Color;
import javax.swing.*;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import javax.swing.table.*;

/**
 *
 * @author KuroNeko
 */
public class Menu extends javax.swing.JFrame {

    String account_id;
    int level, gold, gems, exp;
    int maks;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    CrudImplement cli = new CrudImplement();
    
    /**
     * Creates new form Menu
     */
    
    public Menu() {
        
        initComponents();
        setLocationRelativeTo(null);
        logged();
        levelUp();
        tableHistory();
        setAllText();
        hideAll();
        Main.setVisible(true);
        
    }
    
    
    private void logged(){
        account_id = tcg_osom.Database.getUserId();
        txtNick.setText(tcg_osom.Database.getNickname());
        conn = Database.config();
        String query = "select * from account where account_id = ?";
        try {
            pst = conn.prepareStatement(query);
            pst.setString(1, account_id);
            rs = pst.executeQuery();
            
            if (rs.next()) {
                level = rs.getInt("level");
                maks = level*100;
                exp = rs.getInt("exp");
                gold = rs.getInt("gold");
                gems = rs.getInt("gems");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    private void setAllText(){
        txtLv.setText(String.valueOf("level "+level));
        ProgresExp.setValue(exp);
        txtExp.setText(exp+" / "+maks);
        txtGold.setText(String.valueOf(gold));
        txtGem.setText(String.valueOf(gems));
    }
    
    private void levelUp(){
        if(exp>=maks){
            exp = exp-maks;
            level +=1;
            maks = level*100;
            ProgresExp.setValue(exp);
            ProgresExp.setMaximum(maks);
            int levelUpgold = level*20 + 100;
            int levelUpgems = level*5;
            
            gold += levelUpgold;
            gems += levelUpgems;
            JOptionPane.showMessageDialog(null, "Congrats\n You leveled up to level "+level+"\nYou get "+levelUpgold+" gold and "+levelUpgems+" gems");
            try{
                cli.levelUp(level,account_id);
                cli.setExp(exp, account_id);
                cli.setGold(gold, account_id);
                cli.setGems(gems, account_id);
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
    }
    
    private void hideAll(){
        Main.setVisible(false);
        Tutorial.setVisible(false);
        About.setVisible(false);
        Archieve.setVisible(false);
        History.setVisible(false);
//        Market.setVisible(false);
    }
    
    private void tableHistory(){
        conn = Database.config();
        String query = "select * from history where account_id = ?";
        
        try {
            pst = conn.prepareStatement(query);
            pst.setString(1, account_id);
            rs = pst.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            String [] data = new String[8];
            int i = 1;
            
            while(rs.next()) {
            data[0] = String.valueOf(i);
            data[1] = rs.getString("p1_card");
            data[2] = rs.getString("cpu_card");
            data[3] = rs.getString("p1_hp");
            data[4] = rs.getString("cpu_hp");
            data[5] = rs.getString("win_lose");
            data[6] = rs.getString("play_time");
            data[7] = rs.getString("date");
            dtm.addRow(data);
            i++;
        }
        }
        catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        btnTuts = new javax.swing.ButtonGroup();
        Menu = new javax.swing.JPanel();
        btnMarket = new javax.swing.JButton();
        btnGuide = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnArchieve = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Main = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        imgProfile = new javax.swing.JLabel();
        txtGem = new javax.swing.JLabel();
        txtExp = new javax.swing.JLabel();
        txtLv = new javax.swing.JLabel();
        txtNick = new javax.swing.JLabel();
        ProgresExp = new javax.swing.JProgressBar();
        txtGold = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnCustom = new javax.swing.JLabel();
        btnPlay = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Tutorial = new javax.swing.JPanel();
        btnClose2 = new javax.swing.JButton();
        tutsBg = new javax.swing.JLabel();
        tuts1R1 = new javax.swing.JRadioButton();
        tuts2R1 = new javax.swing.JRadioButton();
        tuts3R1 = new javax.swing.JRadioButton();
        tuts1Prev1 = new javax.swing.JLabel();
        tuts1Nex1 = new javax.swing.JLabel();
        History = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnClose1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Archieve = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        About = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();

        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(51, 51, 51));
        Menu.setPreferredSize(new java.awt.Dimension(1024, 90));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMarket.setBackground(new java.awt.Color(51, 51, 51));
        btnMarket.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMarket.setForeground(new java.awt.Color(255, 255, 255));
        btnMarket.setText("Market");
        btnMarket.setBorder(null);
        btnMarket.setBorderPainted(false);
        btnMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarketActionPerformed(evt);
            }
        });
        Menu.add(btnMarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 40));

        btnGuide.setBackground(new java.awt.Color(51, 51, 51));
        btnGuide.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnGuide.setForeground(new java.awt.Color(255, 255, 255));
        btnGuide.setText("Guide");
        btnGuide.setBorder(null);
        btnGuide.setBorderPainted(false);
        btnGuide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuideActionPerformed(evt);
            }
        });
        Menu.add(btnGuide, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 150, 40));

        btnAbout.setBackground(new java.awt.Color(51, 51, 51));
        btnAbout.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(255, 255, 255));
        btnAbout.setText("About");
        btnAbout.setBorder(null);
        btnAbout.setBorderPainted(false);
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuideMouseEntered(evt);
            }
        });
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        Menu.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 150, 40));

        btnHistory.setBackground(new java.awt.Color(51, 51, 51));
        btnHistory.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnHistory.setText("History");
        btnHistory.setBorder(null);
        btnHistory.setBorderPainted(false);
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        Menu.add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 150, 40));

        btnArchieve.setBackground(new java.awt.Color(51, 51, 51));
        btnArchieve.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnArchieve.setForeground(new java.awt.Color(255, 255, 255));
        btnArchieve.setText("Archieve");
        btnArchieve.setBorder(null);
        btnArchieve.setBorderPainted(false);
        btnArchieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchieveActionPerformed(evt);
            }
        });
        Menu.add(btnArchieve, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 150, 40));

        btnExit.setBackground(new java.awt.Color(51, 51, 51));
        btnExit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        Menu.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 150, 40));

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1024, 60));

        Main.setLayout(null);

        TopPanel.setBackground(new java.awt.Color(51, 51, 51));
        TopPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/Handcard/HC005.png"))); // NOI18N
        TopPanel.add(imgProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 80));

        txtGem.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtGem.setForeground(new java.awt.Color(255, 255, 255));
        txtGem.setText("Gems");
        TopPanel.add(txtGem, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 140, 30));

        txtExp.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtExp.setForeground(new java.awt.Color(255, 255, 255));
        txtExp.setText("0/100");
        TopPanel.add(txtExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 140, -1));

        txtLv.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtLv.setForeground(new java.awt.Color(255, 255, 255));
        txtLv.setText("Level 1");
        TopPanel.add(txtLv, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 90, -1));

        txtNick.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtNick.setForeground(new java.awt.Color(255, 255, 255));
        txtNick.setText("Nickname");
        TopPanel.add(txtNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 90, -1));
        TopPanel.add(ProgresExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 20));

        txtGold.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtGold.setForeground(new java.awt.Color(255, 255, 255));
        txtGold.setText("Gold");
        TopPanel.add(txtGold, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 140, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/Gold.png"))); // NOI18N
        TopPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/Gem.png"))); // NOI18N
        TopPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        btnLogout.setBackground(new java.awt.Color(0, 153, 153));
        btnLogout.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        TopPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 90, 40));

        Main.add(TopPanel);
        TopPanel.setBounds(0, 0, 1020, 110);

        btnCustom.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnCustom.setForeground(new java.awt.Color(255, 255, 255));
        btnCustom.setText("Customize");
        btnCustom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomMouseClicked(evt);
            }
        });
        Main.add(btnCustom);
        btnCustom.setBounds(430, 510, 130, 60);

        btnPlay.setFont(new java.awt.Font("Hack", 1, 36)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(255, 255, 255));
        btnPlay.setText("Play!");
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPlayMouseExited(evt);
            }
        });
        Main.add(btnPlay);
        btnPlay.setBounds(440, 460, 110, 60);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/main_menu.png"))); // NOI18N
        Main.add(jLabel1);
        jLabel1.setBounds(0, 110, 1020, 530);

        jLayeredPane1.add(Main);
        Main.setBounds(0, 0, 1040, 640);

        Tutorial.setBackground(new java.awt.Color(255, 255, 255));
        Tutorial.setLayout(null);

        btnClose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/btnClose.png"))); // NOI18N
        btnClose2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/btnClose-Hover.png"))); // NOI18N
        btnClose2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/btnClose-Hover.png"))); // NOI18N
        btnClose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClose2MouseClicked(evt);
            }
        });
        btnClose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose2ActionPerformed(evt);
            }
        });
        Tutorial.add(btnClose2);
        btnClose2.setBounds(960, 20, 50, 53);

        tutsBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/tutz1.png"))); // NOI18N
        Tutorial.add(tutsBg);
        tutsBg.setBounds(0, 0, 1030, 600);

        btnTuts.add(tuts1R1);
        tuts1R1.setSelected(true);
        tuts1R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuts1R1ActionPerformed(evt);
            }
        });
        Tutorial.add(tuts1R1);
        tuts1R1.setBounds(450, 610, 20, 21);

        btnTuts.add(tuts2R1);
        tuts2R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuts2R1ActionPerformed(evt);
            }
        });
        Tutorial.add(tuts2R1);
        tuts2R1.setBounds(480, 610, 21, 21);

        btnTuts.add(tuts3R1);
        tuts3R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuts3R1ActionPerformed(evt);
            }
        });
        Tutorial.add(tuts3R1);
        tuts3R1.setBounds(510, 610, 21, 21);

        tuts1Prev1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        tuts1Prev1.setText("<-");
        tuts1Prev1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tuts1Prev1MouseClicked(evt);
            }
        });
        Tutorial.add(tuts1Prev1);
        tuts1Prev1.setBounds(430, 610, 20, 20);

        tuts1Nex1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        tuts1Nex1.setText("->");
        tuts1Nex1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tuts1Nex1MouseClicked(evt);
            }
        });
        Tutorial.add(tuts1Nex1);
        tuts1Nex1.setBounds(540, 610, 20, 20);

        jLayeredPane1.add(Tutorial);
        Tutorial.setBounds(0, 0, 1020, 640);

        History.setBackground(new java.awt.Color(61, 61, 61));
        History.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("History Board");
        History.add(jLabel6);
        jLabel6.setBounds(400, 30, 230, 80);

        btnClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/btnClose.png"))); // NOI18N
        btnClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/btnClose-Hover.png"))); // NOI18N
        btnClose1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/btnClose-Hover.png"))); // NOI18N
        btnClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClose1MouseClicked(evt);
            }
        });
        btnClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose1ActionPerformed(evt);
            }
        });
        History.add(btnClose1);
        btnClose1.setBounds(940, 20, 50, 53);

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "P1_Card", "CPU_Card", "P1_HP", "CPU_HP", "Win or Lose", "Play Time", "Date"
            }
        ));
        jTable1.setShowGrid(false);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);

        History.add(jScrollPane1);
        jScrollPane1.setBounds(60, 120, 890, 470);

        jLayeredPane1.add(History);
        History.setBounds(0, 0, 1010, 750);

        Archieve.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/archieve.png"))); // NOI18N
        Archieve.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 700));

        jLayeredPane1.add(Archieve);
        Archieve.setBounds(0, 0, 1020, 640);

        About.setLayout(null);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/btnClose.png"))); // NOI18N
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/btnClose-Hover.png"))); // NOI18N
        btnClose.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/btnClose-Hover.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        About.add(btnClose);
        btnClose.setBounds(960, 10, 50, 53);

        jLayeredPane1.add(About);
        About.setBounds(0, 110, 1020, 530);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarketActionPerformed
        
        
    }//GEN-LAST:event_btnMarketActionPerformed

    private void btnGuideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuideActionPerformed
        hideAll();
        Tutorial.setVisible(true);
    }//GEN-LAST:event_btnGuideActionPerformed

    private void btnGuideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuideMouseEntered
        
    }//GEN-LAST:event_btnGuideMouseEntered

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        hideAll();
        About.setVisible(true);
        
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnArchieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchieveActionPerformed
        this.dispose();
        Archieve arc = new Archieve();
        arc.setVisible(true);
        
    }//GEN-LAST:event_btnArchieveActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
         File data = new File(System.getProperty("user.dir") + "/session.xml");
        if (data.exists()) {
            data.delete();
            Login lF = new Login();
            lF.setVisible(true);
            JOptionPane.showMessageDialog(null, "Berhasil Keluar Aplikasi, \n\nSilahkan Masuk Kembali!!");
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
        GameFrame gf = new GameFrame();
        gf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPlayMouseClicked

    private void btnPlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseEntered
        btnPlay.setForeground(Color.blue);
    }//GEN-LAST:event_btnPlayMouseEntered

    private void btnPlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseExited
        btnPlay.setForeground(Color.white);
    }//GEN-LAST:event_btnPlayMouseExited

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked

    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        About.setVisible(false);
        Main.setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClose1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClose1MouseClicked

    private void btnClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose1ActionPerformed
        History.setVisible(false);
        Main.setVisible(true);
    }//GEN-LAST:event_btnClose1ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void tuts1Prev1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tuts1Prev1MouseClicked
        if(tuts2R1.isSelected()){
            tutsBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/tutz1.png")));
            tuts1R1.setSelected(true);
        }
        else if(tuts3R1.isSelected()){
            tutsBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/tutz2.png")));
            tuts2R1.setSelected(true);
        }
    }//GEN-LAST:event_tuts1Prev1MouseClicked

    private void tuts1Nex1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tuts1Nex1MouseClicked
        if(tuts1R1.isSelected()){
            tutsBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/tutz2.png")));
            tuts2R1.setSelected(true);
        }
        else if(tuts2R1.isSelected()){
            tutsBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/tutz3.png")));
            tuts3R1.setSelected(true);
        }
    }//GEN-LAST:event_tuts1Nex1MouseClicked

    private void tuts1R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuts1R1ActionPerformed
        tutsBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/tutz1.png")));
    }//GEN-LAST:event_tuts1R1ActionPerformed

    private void tuts2R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuts2R1ActionPerformed
        tutsBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/tutz2.png")));
    }//GEN-LAST:event_tuts2R1ActionPerformed

    private void tuts3R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuts3R1ActionPerformed
        tutsBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGSrc/tutz3.png")));
    }//GEN-LAST:event_tuts3R1ActionPerformed

    private void btnClose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClose2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClose2MouseClicked

    private void btnClose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose2ActionPerformed
        Tutorial.setVisible(false);
        Main.setVisible(true);
    }//GEN-LAST:event_btnClose2ActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        hideAll();
        History.setVisible(true);
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnCustomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomMouseClicked
        Deck deck = new Deck();
        this.dispose();
        deck.setVisible(true);

    }//GEN-LAST:event_btnCustomMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel About;
    private javax.swing.JPanel Archieve;
    private javax.swing.JPanel History;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel Menu;
    private javax.swing.JProgressBar ProgresExp;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JPanel Tutorial;
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnArchieve;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnClose1;
    private javax.swing.JButton btnClose2;
    private javax.swing.JLabel btnCustom;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGuide;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMarket;
    private javax.swing.JLabel btnPlay;
    private javax.swing.ButtonGroup btnTuts;
    private javax.swing.JLabel imgProfile;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel tuts1Nex1;
    private javax.swing.JLabel tuts1Prev1;
    private javax.swing.JRadioButton tuts1R1;
    private javax.swing.JRadioButton tuts2R1;
    private javax.swing.JRadioButton tuts3R1;
    private javax.swing.JLabel tutsBg;
    private javax.swing.JLabel txtExp;
    private javax.swing.JLabel txtGem;
    private javax.swing.JLabel txtGold;
    private javax.swing.JLabel txtLv;
    private javax.swing.JLabel txtNick;
    // End of variables declaration//GEN-END:variables

}
